sudo: required
language: node_js
node_js:
  - "7"

after_success:  
- docker pull leanix/pivio-client
- docker run --rm -v $(pwd):/source leanix/pivio-client npm-license-checker
- docker run --rm -v $(pwd):/source leanix/pivio-client pivio -serviceurl "https://test-app-1.leanix.net/services/integrations/v2/pivio/document" -verbose -addfield $APITOKEN

services:
  - docker
